### ISSUE TITLE
Replacement of PhantomJS 

### ISSUE THREAD

**Issue by asoahc** [bpmn-io/bpmn-js-integration#8]
Hi to Berlin,

I working for a project using a custom modeler with bpmn-js. Since release of the new bpmn-js version 7.2, I try to get my tests running again. The template of my tests are basing of this project 'bpmn-js-integration'.
'bpmn-js-integration' is using for testing PhantomJS, but this is no longer state of the art and does not support promise very well. Maybe it will be a good idea to switch from PhantomJS to eg Puppeteer?
Additionally, I saw that the project 'bpmn-js' is using Puppeteer for testing. Why does not use both project the same testing equitment?

Best Regards,
aSoahc

**Comment by pinussilvestrus** [comment]
Thanks for your thoughts, really appreciate it! We will discuss it internally

**Comment by oguzeroglu** [comment]
Hey @asoahc,

For our libraries who are supposed to work on browsers as well, we'd still like to keep the PhantomJS because it is the closest we get to IE. Given that we help people doing business process automation, IE is still used by the people who we target.

Of course, we're keeping up with the modern JS standards too. When we promisified our APIs with bpmn-js@7 we considered getting rid of PhantomJS but we decided not to do that because of the reasons I mentioned. A solution we went for is to polyfill Promises for PhantomJS.

Here's a commit from bpmn-js that we do this exact thing: https://github.com/bpmn-io/bpmn-js/blob/a445144ca93582a0202e951f5ce7f47b2639bac1/test/config/karma.distro.js#L26
